mqtt:
  username: "scrumpi"
  password: "Th3rm"
  port: 1883
  device_prefix: "scrumpi"

devices:
  living_room:
    components:
      temp_sensor:
        type: "ScrumpiTempSensor"
      pressure_sensor:
        type: "ScrumpiBaroSensor"