mqtt:
  username: "scrumpi"
  password: "Th3rm"
  port: 1883
  device_prefix: "therm"

devices:
  stink_button:
    components:
      button:
        type: "Button"
        pin: 14
        pull_up: false
      light:
        type: "Relay"
        signal: "LOW"
        pin: 27
  hvac:
    components:
      fan:
        type: "Fan"
        address: "5f"
        channel: 0
      temp_sensor:
        type: "TemperatureSensor"
      avery_valve:
          type: "Relay"
          signal: "HIGH"
          pin: 9
      bathroom_valve:
        type: "Relay"
        signal: "LOW"
        pin: 10